
services:
  client:
      build: .
      container_name: my_miniserver11
      volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    
  ngin:
      #image: nginx:latest
      build: .
      container_name: my_proxy11
      ports:
        - "80:8080"
      volumes:
        - ./recipient/nginx.conf:/etc/nginx/nginx.conf
